# Generated by Django 5.2 on 2025-04-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='farm_images/')),
                ('farm_type', models.CharField(default='Rent', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='FarmSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='farm_images/')),
                ('farm_type', models.CharField(default='Sale', max_length=4)),
            ],
        ),
    ]
