# Generated by Django 5.2.1 on 2025-06-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_number', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('size', models.FloatField()),
                ('quality', models.CharField(max_length=100)),
                ('farm_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('full_name', models.CharField(max_length=100)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('landlord_name', models.CharField(blank=True, max_length=100)),
                ('landlord_phone', models.CharField(blank=True, max_length=20)),
                ('landlord_email', models.EmailField(blank=True, max_length=254)),
                ('landlord_residence', models.CharField(blank=True, max_length=100)),
                ('landlord_passport', models.CharField(blank=True, max_length=50)),
                ('farm_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='active', max_length=20)),
            ],
        ),
    ]
