# Generated by Django 5.2.1 on 2025-06-16 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalagreement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rental Agreement', 'verbose_name_plural': 'Rental Agreements'},
        ),
        migrations.RenameField(
            model_name='rentalagreement',
            old_name='pdf_file',
            new_name='pdf_document',
        ),
        migrations.RemoveField(
            model_name='rentalagreement',
            name='advance_payment',
        ),
        migrations.RemoveField(
            model_name='rentalagreement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rentalagreement',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='rentalagreement',
            name='status',
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='farm_number',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='initial_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='late_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='witness1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='witness1_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/witnesses/'),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='witness2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rentalagreement',
            name='witness2_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/witnesses/'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='agreement_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='agreement_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='duration_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='farm_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='farm_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='farm_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='farm_size',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='landlord_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='landlord_passport',
            field=models.ImageField(blank=True, null=True, upload_to='passports/landlords/'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='landlord_residence',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='tenant_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='tenant_passport',
            field=models.ImageField(blank=True, null=True, upload_to='passports/tenants/'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='tenant_residence',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='transaction_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='rentalagreement',
            table=None,
        ),
    ]
