# Generated by Django 5.2 on 2025-04-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmrent',
            name='image',
            field=models.FileField(upload_to='farm_images/'),
        ),
        migrations.AlterField(
            model_name='farmsale',
            name='image',
            field=models.FileField(upload_to='farm_images/'),
        ),
    ]
