# Generated by Django 5.2.1 on 2025-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_options_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmrenttransaction',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmsaletransaction',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
