# Generated by Django 5.2.1 on 2025-05-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_farmrent_admin_feedback_farmrent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmsale',
            name='farm_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
