# Generated by Django 5.2.1 on 2025-06-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_purchaseagreement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseagreement',
            old_name='residence',
            new_name='buyer_residence',
        ),
        migrations.RenameField(
            model_name='purchaseagreement',
            old_name='buyer_phone',
            new_name='contact_info',
        ),
    ]
