# Generated by Django 5.2.1 on 2025-05-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_farmsale_farm_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmrent',
            name='farm_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
