# Generated by Django 5.2.1 on 2025-05-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_farmrenttransaction_is_rented_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmrent',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmsale',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
