# Generated by Django 5.2.1 on 2025-06-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_residence_purchaseagreement_buyer_residence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseagreement',
            old_name='buyer_residence',
            new_name='address',
        ),
    ]
