# Generated by Django 5.2 on 2025-04-14 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_farmrent_click_count_farmrent_rent_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmrent',
            name='rent_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FarmRentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('renter_email', models.EmailField(max_length=254)),
                ('rent_date', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.farmrent')),
            ],
        ),
    ]
