# Generated by Django 5.2 on 2025-04-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_farmrent_rent_duration_farmrenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmrenttransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
