# Generated by Django 5.2.1 on 2025-05-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_farmrent_farm_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmrent',
            name='farm_number',
            field=models.CharField(default='NOT GIVEN', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmrent',
            name='ownership_certificate',
            field=models.FileField(default='N/A', upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='farmrent',
            name='passport',
            field=models.ImageField(default='UNKNOWN', upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='farmsale',
            name='farm_number',
            field=models.CharField(default='NOT GIVEN', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmsale',
            name='ownership_certificate',
            field=models.FileField(default='N/A', upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='farmsale',
            name='passport',
            field=models.ImageField(default='UNKNOWN', upload_to='passports/'),
        ),
    ]
