# Generated by Django 5.2 on 2025-04-21 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_farmrenttransaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.farmrent')),
            ],
        ),
    ]
