# Generated by Django 5.2 on 2025-04-24 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_farmsaletransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmsaletransaction',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.farmsale'),
        ),
        migrations.CreateModel(
            name='FarmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='farm_images/')),
                ('farm_rent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.farmrent')),
                ('farm_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.farmsale')),
            ],
        ),
    ]
