# Generated by Django 5.2.1 on 2025-05-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_farmrent_farm_number_alter_farmrent_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmrent',
            name='ownership_certificate',
            field=models.ImageField(default='N/A', upload_to='certificates/'),
        ),
    ]
