# Generated by Django 5.2 on 2025-04-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_farmsaletransaction_farm_farmimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmrent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='farmsale',
            name='image',
        ),
    ]
