# Generated by Django 5.2.1 on 2025-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_farmrent_ownership_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmrent',
            name='ownership_certificate',
            field=models.FileField(default='N/A', upload_to='certificates/'),
        ),
    ]
