# Generated by Django 5.2 on 2025-04-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_farmrent_image_remove_farmsale_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsaletransaction',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmsaletransaction',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmsaletransaction',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farmsaletransaction',
            name='intended_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmsaletransaction',
            name='national_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
