# Generated by Django 5.2 on 2025-04-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_farmsaletransaction_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmrenttransaction',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmrenttransaction',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmrenttransaction',
            name='renter_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmrenttransaction',
            name='residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
