# Generated by Django 5.2.1 on 2025-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_farmrent_ownership_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmrent',
            name='ownership_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='farmsale',
            name='ownership_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
