# Generated by Django 5.2.1 on 2025-06-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_farmrent_ownership_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(max_length=100, unique=True)),
                ('farm_id', models.IntegerField()),
                ('transaction_id', models.IntegerField()),
                ('landlord_name', models.CharField(max_length=200)),
                ('landlord_phone', models.CharField(max_length=20)),
                ('landlord_email', models.EmailField(max_length=254)),
                ('landlord_residence', models.TextField()),
                ('landlord_passport', models.TextField(blank=True, null=True)),
                ('tenant_name', models.CharField(max_length=200)),
                ('tenant_phone', models.CharField(max_length=20)),
                ('tenant_email', models.EmailField(max_length=254)),
                ('tenant_residence', models.TextField()),
                ('tenant_passport', models.TextField(blank=True, null=True)),
                ('farm_location', models.CharField(max_length=200)),
                ('farm_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farm_quality', models.CharField(max_length=100)),
                ('farm_type', models.CharField(max_length=100)),
                ('farm_description', models.TextField(blank=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agreement_date', models.DateTimeField()),
                ('duration_months', models.IntegerField(default=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='rental_agreements/')),
            ],
            options={
                'db_table': 'rental_agreements',
            },
        ),
    ]
